author = "alexandru topliceanu"
baseURL = "http://alexandrutopliceanu.ro/"
canonifyurls = true
googleAnalytics = "UA-24987736-1"
languageCode = "en-us"
publishDir = "docs"
#pygmentsCodeFencesGuessSyntax = true
pygmentsstyle = "bw"
title = "alexandru topliceanu"
theme = "black-and-light"

[params]
  sitename = "Alexandru Topliceanu"
[[menu.main]]
  name = "Github"
  url  = "https://github.com/topliceanu"
[[menu.main]]
  name = "Twitter"
  url  = "https://twitter.com/topliceanu"
[[menu.main]]
  name = "Email"
  url  = "mailto:alexandru.topliceanu@gmail.com"
[[menu.main]]
  name = "Subscribe"
  url  = "http://eepurl.com/cCDKev"
